server:
  port: 8760

---
spring:
  profiles: port1
  application:
    name: Sword-Register1

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
  instance:
    hostname: prot1

---
spring:
  profiles: port2
  application:
    name: Sword-Register2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    hostname: prot2
