server:
  port: 8027

spring:
  application:
    name: Sword-Zuul

eureka:
  client:
    serviceUrl:
      #网关注册到eureka
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    users:
      path: /**
      sensitiveHeaders: #Cookie,Set-Cookie,Authorization
      #url: http://localhost:8019
      serviceId: Sword-Api
