server:
  port: 8082

logging:
  level:
    root: debug

spring:
  application:
    name: Sword-Feng
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root1234
    url: jdbc:mysql://10.0.0.93/feng?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull


mybatis:
  mapper-locations: classpath*:com/huangsiup/feng/dao/*.xml
  type-aliases-package: com.huangsui.feng.dao
