
spring:
  application:
    name: Sword-Register1

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: prot1
