server:
  port: 8023

spring:
  application:
    name: Sword-Api
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: root1234
      url: jdbc:mysql://10.0.0.93/feng?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: root1234
      url: jdbc:mysql://10.0.2.93:3306/feng?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

eureka:
  client:
    serviceUrl:
      #网关注册到eureka
      defaultZone: http://localhost:8761/eureka/

logging:
  #config: classpath:config/logback.xml
  level:
    root: debug

security:
  oauth2:
    client:
      access-token-uri: