spring:
  application:
    name: Sword-Register2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: prot2
